name: message_pack_dart
description: MessagePack implementation for dart. MessagePack is an efficient binary serialization format. It lets you exchange data among multiple languages like JSON.
version: 2.0.1
homepage: https://github.com/sefidgaran/messagePack-dart

environment:
    sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
    test: ^1.3.0
